location/blueprints/auth.py
# -*- coding: utf-8 -*-
from flask import (
    redirect,
    url_for,
    render_template,
    request,
    session,
    Blueprint,
    current_app,
)
from flask_oauthlib.client import OAuthException
from flask_login import (
    login_required,
    login_user,
    logout_user,
    current_user,
)

from location.core import db, oauth, login_manager
from location import models


@login_manager.user_loader
def load_user(user_id):
    return models.User.query.get(int(user_id))

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('root.index'))

    callback = url_for('auth.authorized', _external=True)
    provider = current_app.config.get('OAUTH_PROVIDER')
    return oauth.remote_apps.get(provider).authorize(callback=callback)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return render_template('logged_out.html')


@auth_bp.route('/login/authorized')
def authorized():
    provider = current_app.config.get('OAUTH_PROVIDER')
    resp = oauth.remote_apps.get(provider).authorized_response()

    if resp is None:
        message = "Access denied: reason={} error={}".format(
            request.args['error_reason'],
            request.args['error_description'],
        )
        return render_template('restricted.html', context=dict(message=message)), 400

    if isinstance(resp, OAuthException):
        message = "Access denied: {}".format(
            resp.message
        )
        return render_template('restricted.html', context=dict(message=message)), 400

    session['access_token'] = (resp['access_token'], '')
    provider = current_app.config.get('OAUTH_PROVIDER')
    identity_endpoint = current_app.oauth_provider.identity_endpoint()
    auth_response = oauth.remote_apps.get(provider).get(identity_endpoint)

    allowed_domain = current_app.config.get('ALLOWED_DOMAIN')
    if allowed_domain and allowed_domain != current_app.oauth_provider.user_domain(auth_response):
        message = "Your email is not authorized"
        return render_template('restricted.html', context=dict(message=message)), 400

    user = models.User.query.filter_by(oauth_id=auth_response.data['id']).first()

    # Save a refreshed access token
    if user and user.oauth_access_token != resp['access_token']:
        user.oauth_access_token = resp['access_token']
        db.session.add(user)
        db.session.commit()

    if not user:
        user = models.User(
            oauth_access_token=resp['access_token'],
            **current_app.oauth_provider.user_info(auth_response)
        )
        db.session.add(user)
        db.session.commit()

    login_user(user)

    return redirect(url_for('root.index'))

location/blueprints/teams.py
# -*- coding: utf-8 -*-
from flask import (
    redirect,
    request,
    url_for,
    render_template,
    Blueprint,
)
from flask_login import (
    login_required,
    current_user,
)

from location import models
from location.core import db

teams_bp = Blueprint('teams', __name__, url_prefix='/teams')


@teams_bp.route('/')
@login_required
def index():
    teams = models.Team.query.all()
    return render_template('teams/index.html', teams=teams)


@teams_bp.route('/create', methods=['POST'])
@login_required
def create():
    team = models.Team()
    team.name = request.form['name']
    db.session.add(team)
    db.session.commit()

    return redirect('/teams')


@teams_bp.route('/delete')
@login_required
def delete():
    team = models.Team.query.get(request.args['team_id'])
    db.session.delete(team)
    db.session.commit()

    return redirect('/teams')


@teams_bp.route('/<int:team_id>')
@login_required
def view(team_id):
    team = models.Team.query.get(team_id)
    return render_template('teams/view.html', team=team)


@teams_bp.route('/<int:team_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(team_id):
    team = models.Team.query.get(team_id)
    all_users = models.User.query.order_by('name')

    if request.method == 'POST':
        checked_user_ids = request.form.getlist('users', int)
        for user in all_users:
            if user.id in checked_user_ids:
                if user not in team.users:
                    team.users.append(user)
            else:
                if user in team.users:
                    team.users.remove(user)

        db.session.add(team)
        db.session.commit()
        return redirect(url_for('teams.edit', team_id=team_id))
    else:
        users_in_team = team.users
        return render_template('teams/edit.html', team=team, all_users=all_users, users_in_team=users_in_team)


@teams_bp.route('/<int:team_id>/join')
@login_required
def join(team_id):
    team = models.Team.query.get(team_id)
    if current_user not in team.users:
        team.users.append(current_user)
        db.session.add(team)
        db.session.commit()
    return redirect('/teams')


@teams_bp.route('/<int:team_id>/leave')
@login_required
def leave(team_id):
    team = models.Team.query.get(team_id)
    if current_user in team.users:
        team.users.remove(current_user)
        db.session.add(team)
        db.session.commit()
    return redirect('/teams')

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
    <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
    <link rel="stylesheet" href="/static/style.css" type="text/css">
</head>
<body>

<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />


<div id="content">
    <div id="people_section">
        <div id="people_header">
            Everyone
        </div>
        <div id="people">
            &nbsp;
        </div>
    </div>
    <div id="map"></div>
</div>

<div id="map_footer">
    <div class="link">
    {% if current_user.teams %}
        {% for team in current_user.teams %}
        <a href="{{ url_for('teams.view', team_id=team.id)  }}">{{team.name}}</a> ♦
        {% endfor %}
    {% endif %}
        <a href="{{ url_for('teams.index') }}">View all teams</a>
    </div>

    <div class="link">
    </div>

    <div>
        <a href="{{ url_for('auth.logout') }}">Logout</a>
    </div>
</div>

<script>
var team_id = null;
</script>
<script src="/static/geo.js"></script>

</body>
</html>

templates/logged_out.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <link rel="stylesheet" href="/static/style.css" type="text/css">
</head>
<body>

<h3>Thanks</h3>
<p>You've been logged out. Click <a href="{{ url_for('auth.login') }}">here</a> to log back in.</p>

</body>
</html>

templates/restricted.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>Teams</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <link rel="stylesheet" href="/static/style.css" type="text/css">
</head>
<body>
    <div class="error">
        You do not have access to this resource. Apologies!
    </div>

    <div>&nbsp;</div>

    {% if context %}
    <div>
        <small>{{ context.get('message','') }}</small>
    </div>
    {% endif %}

    <div>
        <a href="{{ url_for('auth.login') }}">Login</a>
    </div>

</body>
</htmL>